//! Quasar-native lint engine over the parserless IDL build surface.
//!
//! The linter consumes the same `Idl` object generated by the derive/inventory
//! `idl-build` path. It does not parse Rust source or resurrect the deleted
//! parser-based lint stack.

mod report;
mod rules;
mod surface;

use crate::types::Idl;
pub use {
    report::{Diagnostic, LintConfig, LintReport, RuleCode, Severity},
    surface::{
        load_lockfile, lock_path, save_lockfile, LockfileError, ProgramSurface, LOCK_FILE_NAME,
    },
};

/// Run single-build audit rules against the current IDL.
pub fn run(idl: &Idl, config: &LintConfig) -> LintReport {
    rules::preflight(&ProgramSurface::from_idl(idl), config)
}

/// Compare a previous release surface with the current candidate.
pub fn diff(old: &ProgramSurface, new: &ProgramSurface) -> LintReport {
    rules::diff(old, new)
}

/// Run single-build rules and, when `old` is present, release diff rules.
pub fn run_with_optional_diff(
    idl: &Idl,
    old: Option<&ProgramSurface>,
    config: &LintConfig,
) -> LintReport {
    let surface = ProgramSurface::from_idl(idl);
    let mut report = rules::preflight(&surface, config);
    if let Some(old) = old {
        report.extend(rules::diff(old, &surface));
    }
    report
}
